services:
    backend:
        image: todo-backend
        build:
            context: todo-backend

    mongo:
        image: mongo-bongo
        build:
            context: mongo-dev
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: the_database

    redis:
        image: redis
        volumes:
            - redis:/data
        command: ['redis-server', '--appendonly', 'yes']

    front:
        image: todo-front
        container_name: todo-front
        build:
            context: todo-frontend

    proxy:
        image: todo-proxy
        build:
            context: nginx
        restart: unless-stopped
        ports:
            - 80:80

volumes:
    redis:
