services:
    backend:
        image: todo-backend
        build:
            context: todo-backend
            dockerfile: dev.Dockerfile
        volumes:
            - ./todo-backend:/usr/src/app

    mongo:
        image: mongo-bongo
        build:
            context: mongo-dev
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: the_database

    redis:
        image: redis
        volumes:
            - ./redis_data_dev:/data
        command: ['redis-server', '--appendonly', 'yes']

    front:
        image: todo-front-dev
        container_name: todo-front-dev
        build:
            context: todo-frontend
            dockerfile: dev.Dockerfile
        volumes:
            - ./todo-frontend:/usr/src/app

    proxy:
        image: todo-proxy
        build:
            context: nginx
        restart: unless-stopped
        ports:
            - 8080:80
