services:
    backend:
        image: todo-backend
        build:
            context: todo-backend
            dockerfile: dev.Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./todo-backend:/usr/src/app
    mongo:
        image: mongo-bongo
        build:
            context: mongo-dev
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: the_database
    redis:
        image: redis
        volumes:
            - ./redis_data_dev:/data
        command: ['redis-server', '--appendonly', 'yes']
